apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argocd
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
